### ISSUE TITLE
Wrong PayPalCheckout.json url link in cartfile

### ISSUE THREAD

**Issue by SerggioC** [paypal/paypalcheckout-samples-ios#9]
should be `binary "https://github.com/paypal/paypalcheckout-ios/raw/main/Carthage/PayPalCheckout.json" ~> 0.42.0`
or omit the version

**Comment by jaxdesmarais** [comment]
Hello @SerggioC -

We've got a couple of PRs up now that include this update, along with several other updates, as our SDK has changed quite a bit since the current version used in the samples. While you're more than welcome to use the current sample, you would need to edit your `Cartfile` with the new binary.

Once the new samples are merged, I will update this issue to let you know as they will include this change.

**Comment by jaxdesmarais** [comment]
Hello @SerggioC -

The sample apps (Objective-C and Swift) have now both been merged. Closing out this issue as this is now resolved, but if you run into anything else, please don't hesitate to reach back out to us!
